document.writeln('<div id="hosting_informer" style="width: 250px; padding: 0 0; margin: 0 0;">');
document.writeln('<table cellspacing="0" cellpadding="0" border="0" class="host-inner-table">');
document.writeln('<thead><th>Хостинг</th><th>Цена</th></thead><tbody>');
document.writeln('<tr valign="top" class="host-row-odd pointer" onclick="window.location.href=\'http://'+server+'/hosting/index?plan=Host-Lite-0910&referer='+rid+'&rid='+rid+'\';">');
document.writeln('    <td><span class="title">Host-Lite</span><br />');
document.writeln('    <small><nobr>HDD: 5Гб,</nobr>');
document.writeln('    <nobr>БД: нет,</nobr><br />');
document.writeln('    <nobr>Доменов: 10,</nobr>');
document.writeln('    <nobr>PHP&nbsp;5.2: нет</small>');
document.writeln('    </td><td width="55px"><div class="price">');
document.writeln('    <small>&nbsp;<span>руб.</span><br />&nbsp;мес.</small></div>');
document.writeln('    <div class="price"><b><big>99</big></div></td></tr>');
document.writeln('<tr valign="top" class="host-row-even pointer" onclick="window.location.href=\'http://'+server+'/hosting/index?plan=Host-0-0910&referer='+rid+'&rid='+rid+'\';">');
document.writeln('    <td><span class="title">Host-0</span><br />');
document.writeln('    <small><nobr>HDD: 1Гб,</nobr>');
document.writeln('    <nobr>БД: 1,</nobr><br />');
document.writeln('    <nobr>Доменов: 1,</nobr>');
document.writeln('    <nobr>PHP&nbsp;5.2: есть</small>');
document.writeln('    </td><td width="55px"><div class="price">');
document.writeln('    <small>&nbsp;<span>руб.</span><br />&nbsp;мес.</small></div>');
document.writeln('    <div class="price"><b><big>149</big></div></td></tr>');
document.writeln('<tr valign="top" class="host-row-odd pointer" onclick="window.location.href=\'http://'+server+'/hosting/index?plan=Host-1-1209&referer='+rid+'&rid='+rid+'\';">');
document.writeln('    <td><span class="title">Host-1</span><br />');
document.writeln('    <small><nobr>HDD: 5Гб,</nobr>');
document.writeln('    <nobr>БД: 10,</nobr><br />');
document.writeln('    <nobr>Доменов: 10,</nobr>');
document.writeln('    <nobr>PHP&nbsp;5.2: есть</small>');
document.writeln('    </td><td width="55px"><div class="price">');
document.writeln('    <small>&nbsp;<span>руб.</span><br />&nbsp;мес.</small></div>');
document.writeln('    <div class="price"><b><big>249</big></div></td></tr>');
document.writeln('<tr valign="top" class="host-row-even pointer" onclick="window.location.href=\'http://'+server+'/hosting/index?plan=Host-2-1209&referer='+rid+'&rid='+rid+'\';">');
document.writeln('    <td><span class="title">Host-2</span><br />');
document.writeln('    <small><nobr>HDD: 7Гб,</nobr>');
document.writeln('    <nobr>БД: 20,</nobr><br />');
document.writeln('    <nobr>Доменов: 20,</nobr>');
document.writeln('    <nobr>PHP&nbsp;5.2: есть</small>');
document.writeln('    </td><td width="55px"><div class="price">');
document.writeln('    <small>&nbsp;<span>руб.</span><br />&nbsp;мес.</small></div>');
document.writeln('    <div class="price"><b><big>349</big></div></td></tr>');
document.writeln('<tr valign="top" class="host-row-odd pointer" onclick="window.location.href=\'http://'+server+'/hosting/index?plan=Host-3-0413&referer='+rid+'&rid='+rid+'\';">');
document.writeln('    <td><span class="title">Host-3</span><br />');
document.writeln('    <small><nobr>HDD: 10Гб,</nobr>');
document.writeln('    <nobr>БД: 30,</nobr><br />');
document.writeln('    <nobr>Доменов: 30,</nobr>');
document.writeln('    <nobr>PHP&nbsp;5.2: есть</small>');
document.writeln('    </td><td width="55px"><div class="price">');
document.writeln('    <small>&nbsp;<span>руб.</span><br />&nbsp;мес.</small></div>');
document.writeln('    <div class="price"><b><big>449</big></div></td></tr>');
document.writeln('<tr valign="top" class="host-row-even pointer" onclick="window.location.href=\'http://'+server+'/hosting/index?plan=Host-CMS-0413&referer='+rid+'&rid='+rid+'\';">');
document.writeln('    <td><span class="title">Host-CMS</span><br />');
document.writeln('    <small><nobr>HDD: 25Гб,</nobr>');
document.writeln('    <nobr>БД: 30,</nobr><br />');
document.writeln('    <nobr>Доменов: 30,</nobr>');
document.writeln('    <nobr>PHP&nbsp;5.2: есть</small>');
document.writeln('    </td><td width="55px"><div class="price">');
document.writeln('    <small>&nbsp;<span>руб.</span><br />&nbsp;мес.</small></div>');
document.writeln('    <div class="price"><b><big>799</big></div></td></tr>');
document.writeln('</tbody></table></div>');
