document.writeln('<div id="hosting_informer" style="width: 250px; padding: 0 0; margin: 0 0;">');
document.writeln('<table cellspacing="0" cellpadding="0" border="0" class="host-inner-table">');
document.writeln('<thead><th>Виртуальный сервер</th><th style="padding-left:2em;">Цена</th></thead><tbody>');
document.writeln('<tr valign="top" class="host-row-odd pointer" onclick="window.location.href=\'http://'+server+'/vps/index?plan=VPS-1-0615&referer='+rid+'&rid='+rid+'\';">');
document.writeln('    <td width="140px"><span class="title">VPS-1</span><br />');
document.writeln('    <small><nobr>Процессор: 500МГц,</nobr><br />');
document.writeln('    <nobr>HDD: 20Гб,</nobr>');
document.writeln('    <nobr>Память: 256Мб</nobr></small>');
document.writeln('    </td><td><div class="price">');
document.writeln('    <small>&nbsp;<span>руб.</span><br />&nbsp;мес.</small></div>');
document.writeln('    <div class="price"><b>');
document.writeln('    <big>175</big></div></td></tr>');
document.writeln('<tr valign="top" class="host-row-even pointer" onclick="window.location.href=\'http://'+server+'/vps/index?plan=VPS-2-0615&referer='+rid+'&rid='+rid+'\';">');
document.writeln('    <td width="140px"><span class="title">VPS-2</span><br />');
document.writeln('    <small><nobr>Процессор: 1000МГц,</nobr><br />');
document.writeln('    <nobr>HDD: 30Гб,</nobr>');
document.writeln('    <nobr>Память: 512Мб</nobr></small>');
document.writeln('    </td><td><div class="price">');
document.writeln('    <small>&nbsp;<span>руб.</span><br />&nbsp;мес.</small></div>');
document.writeln('    <div class="price"><b>');
document.writeln('    <big>350</big></div></td></tr>');
document.writeln('<tr valign="top" class="host-row-odd pointer" onclick="window.location.href=\'http://'+server+'/vps/index?plan=VPS-3-0615&referer='+rid+'&rid='+rid+'\';">');
document.writeln('    <td width="140px"><span class="title">VPS-3</span><br />');
document.writeln('    <small><nobr>Процессор: 2000МГц,</nobr><br />');
document.writeln('    <nobr>HDD: 60Гб,</nobr>');
document.writeln('    <nobr>Память: 1024Мб</nobr></small>');
document.writeln('    </td><td><div class="price">');
document.writeln('    <small>&nbsp;<span>руб.</span><br />&nbsp;мес.</small></div>');
document.writeln('    <div class="price"><b>');
document.writeln('    <big>700</big></div></td></tr>');
document.writeln('<tr valign="top" class="host-row-even pointer" onclick="window.location.href=\'http://'+server+'/vps/index?plan=VPS-4-0615&referer='+rid+'&rid='+rid+'\';">');
document.writeln('    <td width="140px"><span class="title">VPS-4</span><br />');
document.writeln('    <small><nobr>Процессор: 2x2000МГц,</nobr><br />');
document.writeln('    <nobr>HDD: 90Гб,</nobr>');
document.writeln('    <nobr>Память: 2048Мб</nobr></small>');
document.writeln('    </td><td><div class="price">');
document.writeln('    <small>&nbsp;<span>руб.</span><br />&nbsp;мес.</small></div>');
document.writeln('    <div class="price"><b>');
document.writeln('    <big>1 400</big></div></td></tr>');
document.writeln('<tr valign="top" class="host-row-even pointer" onclick="window.location.href=\'http://'+server+'/vps/index?plan=VPS-5-0615&referer='+rid+'&rid='+rid+'\';">');
document.writeln('    <td width="140px"><span class="title">VPS-5</span><br />');
document.writeln('    <small><nobr>Процессор: 4x2000МГц,</nobr><br />');
document.writeln('    <nobr>HDD: 120Гб,</nobr>');
document.writeln('    <nobr>Память: 4096Мб</nobr></small>');
document.writeln('    </td><td><div class="price">');
document.writeln('    <small>&nbsp;<span>руб.</span><br />&nbsp;мес.</small></div>');
document.writeln('    <div class="price"><b>');
document.writeln('    <big>2 800</big></div></td></tr>');
document.writeln('</tbody></table></div>');
