(function(w,d){function bindOnReady(handler){var called=false,doc=d.documentElement;function ready(){if(called)return;called=true;handler();}
function tryScroll(){if(called)return;try{doc.doScroll("left");ready();}
catch(e){setTimeout(tryScroll,10);}}
if(d.addEventListener){d.addEventListener("DOMContentLoaded",ready,false);}
else if(d.attachEvent){try{var isFrame=w.frameElement!=null;}
catch(e){}
if(doc.doScroll&&!isFrame){tryScroll();}
d.attachEvent("onreadystatechange",function(){if(d.readyState==="complete"){ready();}})}
else if(w.addEventListener){w.addEventListener('load',ready,false);}
else if(w.attachEvent){w.attachEvent('onload',ready);}
else{var fn=w.onload;w.onload=function(){fn&&fn();ready();}}}
function sapeRTBonReady(){var w=window;sapeRtbHandler_95=typeof w.sapeRtbHandler_95!=='undefined'?w.sapeRtbHandler_95:{addEventListenerCrossBrowser:function(target,type,handler){if(target.addEventListener){target.addEventListener(type,handler,false);}
else if(target.attachEvent){target.attachEvent("on"+type,function(event){handler.call(target,event)});}
else{throw'Cannot add event listener: no Event API support in client'}},hasClass:function(e,c){return(" "+e.className+" ").indexOf(" "+c+" ")>-1;},sapeRTBClosePopup:function(event){this.parentNode.style.display='none';this.parentNode.parentNode.removeChild(this.parentNode);if(event.preventDefault){event.preventDefault();}
return false;},sapeRTBGetBranchNumber:function(data,branch){for(var key in data.branches){if(data.branches.hasOwnProperty(key)){if(data.branches[key].join(',')==branch){return key;}}}},sapeRTBStartBranch:function(data){return this.sapeRTBDrawBanner(data,data.branches[data.branch_number][data.partner_number]);},sapeRTBTrackingCode:function(sectionData,status){var pixel=document.createElement('img'),partner=sectionData.branches[sectionData.branch_number][sectionData.partner_number-(status==3?1:0)],src='//www.acint.net/pxl/'+status+'?dp='+partner+'&id='+this.srtbid+'.'+sectionData.id+'&sid='+this.sid;if(partner==32){src+='&slot='+sectionData.tml_slot;}
pixel.alt="";pixel.src=src;pixel.style.width=1;pixel.style.height=1;pixel.style.position='fixed';pixel.style.left='-100px';pixel.style.top='-100px';pixel.style.opacity=0;if(document.body!=null){document.body.appendChild(pixel);}else if(document.getElementsByTagName('body').length){document.getElementsByTagName('body')[0].appendChild(pixel);}},previousTag:function(node){var node=node.previousSibling;return(node&&node.nodeType!=1)?this.previousTag(node):node;},nextTag:function(node){var node=node.nextSibling;return(node&&node.nodeType!=1)?this.nextTag(node):node;},firstChildTag:function(node){var node=node.firstChild;return(node&&node.nodeType!=1)?this.nextTag(node):node;},lastChildTag:function(node){var node=node.lastChild;return(node&&node.nodeType!=1)?this.previousTag(node):node;},sapeRTBDrawBanner:function(data,partner){var dv,result=false;dv=document.getElementById('SRTB_'+data.id);if((dv&&dv.children.length===0)||data.mobile){if(data.popup&&!data.mobile){result=this.sapeRTBDrawBannerPopup(dv,data,partner);}else if(partner==7){result=this.sapeRTBInsertBtwElement(dv,data);}else if(partner==46){result=this.sapeRTBInsertMmbElement(dv,data);}else if(partner==0){result=this.sapeRTBInsertStubElement(dv,data);}else if(partner==16){result=this.sapeRTBInsertSasElement(dv,data);}}else if(!dv&&data.popup){dv=document.createElement('div');dv.id='SRTB_'+data.id;result=this.sapeRTBDrawBannerPopup(dv,data,partner);if(result){document.body.appendChild(dv);}}
return result;},sapeRTBDrawBannerPopup:function(dv,data,partner){var result=false;if(this.sapeRTBisMobile()&&!data.mobile){return result;}
var acl=document.createElement('a'),partner_div=document.createElement('div');partner_div.id='SRTB_PARTNER_'+data.id;partner_div.style.position='relative';acl.innerHTML='<img style="border:0;outline:none;" src="//cdn-rtb.sape.ru/rtb-b/i/close.png">'
acl.style.position='absolute';acl.style.border=0;acl.style.outline='none';acl.style.zIndex=9999;acl.style.display="block";acl.href='#';acl.className='SRTB_CLOSE';dv.style.position='fixed';dv.style.width=data.w+'px';dv.style.height=data.h+'px';partner_div.style.width=data.w+'px';partner_div.style.height=data.h+'px';switch(data.popup){case 1:dv.style.right='0px';dv.style.bottom='0px';dv.style.margin='1px';acl.style.left='-16px';acl.style.top='-16px';break;case 2:dv.style.left='0px';dv.style.bottom='0px';dv.style.margin='1px';acl.style.right='-16px';acl.style.top='-16px';break;case 3:dv.style.right='0px';dv.style.top='0px';dv.style.margin='1px';acl.style.left='-16px';acl.style.top='0px';break;case 4:dv.style.left='0px';dv.style.top='0px';dv.style.margin='1px';acl.style.right='-16px';acl.style.top='0';break;case 5:dv.style.left='50%';dv.style.top='0px';dv.style.margin="1px 1px 1px "+(-parseInt(data.w/2)+"px");acl.style.right='-16px';acl.style.top='-16px';break;case 6:dv.style.left='50%';dv.style.bottom='0px';dv.style.margin="1px 1px 1px "+(-parseInt(data.w/2)+"px");acl.style.right='-16px';acl.style.top='-16px';break;default:dv.style.right='0px';dv.style.bottom='0px';acl.style.left='-16px';acl.style.bottom='-16px';}
dv.style.right='0px';dv.style.bottom='0px';dv.style.zIndex="9999";if(partner==7){result=this.sapeRTBInsertBtwElement(partner_div,data);}if(partner==46){result=this.sapeRTBInsertMmbElement(partner_div,data);}if(partner==0){result=this.sapeRTBInsertStubElement(partner_div,data);}if(partner==16){result=this.sapeRTBInsertSasElement(partner_div,data);}if(result){document.body.appendChild(dv);dv.appendChild(acl);dv.appendChild(partner_div);this.addEventListenerCrossBrowser(this.firstChildTag(dv),'click',this.sapeRTBClosePopup);}
return result;},sapeRTBInsertSasElement:function(p,data){if(typeof data.htmlData==='undefined'){var fl=0,win=window,u=null;try{u=encodeURIComponent(w.top.location.toString());}catch(e){};while(win!=win.top){fl++;win=win.parent;}
if(typeof data.sc_id!=='undefined'){var src='//ssp-rtb.sape.ru/data/?callback=sapeRTBreadResponse&srtbid='+this.srtbid+'&scids='+data.sc_id+'&sx='+w.screen.width+'&sy='+w.screen.height+'&ref='+encodeURIComponent(w.document.referrer)+
(u!==null?'&u='+u:'')+'&allimps=0'+'&fl='+fl,script=d.createElement('script');script.src=src;script.async=true;script=this.addScriptLoadListener(script,data.id,null);document.body.appendChild(script);}}else{p.innerHTML=p.innerHTML+data.htmlData;this.evalNode(p);}
return true;},sapeRTBRunSas:function(){var result=false;if(this.srtbid>0&&this.sasIds.length>0){var scids=this.sasIds.join();w.sapeRtbHandler_95=this;if(scids!=''){var fl=0,win=window,u=null;try{u=encodeURIComponent(w.top.location.toString());}catch(e){};while(win!=win.top){fl++;win=win.parent;}
var src='//ssp-rtb.sape.ru/data/?callback=sapeRTBreadResponse&srtbid='+this.srtbid+'&scids='+scids+'&sx='+w.screen.width+'&sy='+w.screen.height+'&ref='+encodeURIComponent(w.document.referrer)+
(u!==null?'&u='+u:'')+'&allimps=1'+'&fl='+fl,script=d.createElement('script');script.src=src;script=this.addScriptLoadListener(script,16,'partnerId');d.body.appendChild(script);result=true;}}
return result;},sapeRTBInsertBtwElement:function(p,data){if(typeof data.btw_id==='undefined'){return false;}
var dv=document.createElement("div"),e=document.createElement("script");dv.id='b_script_'+data.btw_id;e.type="text/javascript";e.async=true;e.src='//dispenser-rtb.sape.ru/sections/2/'+data.btw_id+'.js';if(data.popup&&w.addEventListener){w.addEventListener('message',function(event){if(event.data==="[object Object]"||(event.data.is_show&&event.data.section==data.btw_id&&!p.hasAttribute('data-hide'))){p.style.display='block'}},false);}
e=this.addScriptLoadListener(e,data.id,null);dv.appendChild(e);p.appendChild(dv);return true;},sapeRTBInsertMmbElement:function(p,data){if(typeof data.site_id==='undefined'||typeof data.params==='undefined'){return false;}
var e=document.createElement("script");e.type="text/javascript";e.async=true;e.src="http://w1w.clientcare.ru/?theme="+data.theme_id+"&id="+data.site_id+data.params;var t=document.getElementsByTagName("script")[0];e=this.addScriptLoadListener(e,data.id,null);t.parentNode.insertBefore(e,t);return true;},sapeRTBInsertStubElement:function(p,data){var stubs=new Array(),has_stub_partner=false;if(data.partner_number==0){if(typeof data.admin_stubs!=='undefined'){stubs=data.admin_stubs;}else if(typeof data.stubs!=='undefined'){stubs=data.stubs;}}else{for(var i=0;i<data.branches.length;i++){if(data.branches[i][0]==0){has_stub_partner=true;}}
if(typeof data.admin_stubs!=='undefined'&&!has_stub_partner){stubs=stubs.concat(data.admin_stubs);}
if(typeof data.stubs!=='undefined'){stubs=stubs.concat(data.stubs);}}
if(stubs.length==0){return false;}
var stub=stubs[Math.floor(Math.random()*stubs.length)];if(stub.async==1){p.innerHTML=stub.html;this.evalNode(p);}else{this.sapeRTBInsertStubSyncElement(p,stub.html,data.w,data.h);}
return true;},sapeRTBInsertStubSyncElement:function(p,html,width,height){var frame=document.createElement('iframe'),id='FRAME_'+p.id;frame.setAttribute('scrolling','no');frame.setAttribute('frameborder','0');frame.setAttribute('marginwidth','0');frame.setAttribute('marginheight','0');frame.setAttribute('width',width);frame.setAttribute('height',height);frame.id=id;frame.src='about:blank'
p.appendChild(frame);window.sapeDrawUserBanner=function(n,id,html){var d;try{if(document.all&&!window.opera){d=window.frames[id].document;}else if(document.getElementById){d=document.getElementById(id).contentDocument;}}catch(e){;}
if(n>0){if(typeof d==='undefined'){setTimeout(sapeDrawUserBanner,100,--n,id,html);}else{d.open();d.write(html);d.close();}}}
sapeDrawUserBanner(10,id,html);return true;},sapeRTBisMobile:function(){return(/android|webos|iphone|ipad|ipod|blackberry|iemobile|opera mini/i.test(navigator.userAgent.toLowerCase()));},nodeScriptClone:function(node){var script=document.createElement("script");script.text=node.innerHTML;for(var i=node.attributes.length-1;i>=0;i--){script.setAttribute(node.attributes[i].name,node.attributes[i].value);}
return script;},evalNode:function(node){if(node.tagName==='SCRIPT'){node.parentNode.replaceChild(this.nodeScriptClone(node),node);}else{var i=0;var children=node.childNodes;while(i<children.length){this.evalNode(children[i++]);}}
return node;},inIframe:function(){try{return window.self!==window.top;}catch(e){return true;}},generateSessionId:function(){return'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(c){var r=Math.random()*36|0;return r.toString(36);});},insertAfter:function(referenceNode,newNode){if(referenceNode.nextSibling){referenceNode.parentNode.insertBefore(newNode,referenceNode.nextSibling);}else{referenceNode.parentNode.appendChild(newNode);}},addScriptLoadListener:function(script,id,type){if(type==null){type='sectionId';}
script.setAttribute('data-srtb-id',id);script.setAttribute('data-srtb-type',type);if(script.dataset){script.dataset.srtbId=id;script.dataset.srtbType=type;}
this.addEventListenerCrossBrowser(script,'error',function(e){var msg,id,type;if(this.dataset){id=this.dataset.srtbId;type=this.dataset.srtbType;this.dataset.srtbError=1;}else{id=this.getAttribute('data-srtb-id');type=this.getAttribute('data-srtb-type');this.setAttribute('data-srtb-error',1);}
var msg={provider:'sRTBMsg',act:'showNext'};msg[type]=id;var w=window;w.postMessage(JSON.stringify(msg),'*');while(w!=w.parent){w=w.parent;w.postMessage(JSON.stringify(msg),'*');}});return script;}};if(typeof sapeRtbHandler_95.srtbid=='undefined'){sapeRtbHandler_95.srtbid=95;sapeRtbHandler_95.sid=sapeRtbHandler_95.generateSessionId();sapeRtbHandler_95.ads=[{"id":175,"w":160,"h":600,"popup":0,"mobile":0,"done":0,"branches":[[7,16,0]],"stubs":[{"html":"<ins class=\"adsbygoogle\" style=\"display:inline-block;width:160px;height:600px\" data-ad-client=\"ca-pub-2430461256907383\" data-ad-slot=\"2540484325\"><\/ins><script>(adsbygoogle = window.adsbygoogle || []).push({});<\/script>","async":true}],"btw_id":"392469","sc_id":"161461"},{"id":55746,"w":300,"h":250,"popup":2,"mobile":0,"done":0,"branches":[[7,16,0]],"btw_id":"392496","sc_id":"161463"},{"id":80385,"w":468,"h":60,"popup":0,"mobile":0,"done":0,"branches":[[7,16,0]],"stubs":[{"html":"<ins class=\"adsbygoogle\" style=\"display:block\" data-ad-client=\"ca-pub-2430461256907383\" data-ad-slot=\"6297638721\" data-ad-format=\"auto\"><\/ins><script>(adsbygoogle = window.adsbygoogle || []).push({});<\/script>","async":false}],"btw_id":"400748","sc_id":"172485"},{"id":177,"w":0,"h":0,"mobile":1,"done":0,"branches":[[46,0]],"theme_id":128,"site_id":95,"params":"&f1=1&f2=1&f3=1"}];sapeRtbHandler_95.addEventListenerCrossBrowser(w,'message',function(e){var eventData;try{eventData=JSON.parse(e.data);}catch(err){eventData=e.data;}
if(eventData.provider!==undefined&&eventData.provider!==null&&eventData.provider=='sRTBMsg'){if(eventData.act!==undefined&&eventData.act!==null){if(eventData.act=='showNext'){if(w.hasOwnProperty('sapeRtbHandler_95')&&w.sapeRtbHandler_95){var sapeRtbHandler=window.sapeRtbHandler_95;for(var b=0;b<sapeRtbHandler.ads.length;b++){if((typeof eventData.republerSectionId!=='undefined'&&sapeRtbHandler.ads[b].rpbl_id==eventData.republerSectionId)||(typeof eventData.republerSectionId=='undefined'&&typeof eventData.sectionId!=='undefined'&&sapeRtbHandler.ads[b].id==eventData.sectionId)||(typeof eventData.republerSectionId=='undefined'&&typeof eventData.sectionId=='undefined'&&typeof eventData.partnerId!=='undefined'&&sapeRtbHandler.ads[b].current_partner==eventData.partnerId)){var was_shown=false,noad=true;while(!was_shown){sapeRtbHandler.ads[b].partner_number++;var sectionData=sapeRtbHandler.ads[b];if(noad){sapeRtbHandler.sapeRTBTrackingCode(sectionData,3);noad=false;}
if(typeof sectionData.branches[sectionData.branch_number][sectionData.partner_number]=='undefined'){var el=d.getElementById('SRTB_'+eventData.sectionId);if(el){el.style.display='none';el.setAttribute('data-hide','1');}
break;}else{var el=document.getElementById('SRTB_'+sectionData.id);if(el){if(!sectionData.popup&&!sectionData.mobile){var new_el=el.cloneNode(false);sapeRtbHandler.insertAfter(el,new_el);}
el.style.display='none';el.id='SRTB_'+sectionData.id+'_'+sectionData.branches[sectionData.branch_number][sectionData.partner_number-1];}
was_shown=sapeRtbHandler.sapeRTBDrawBanner(sectionData,sectionData.branches[sectionData.branch_number][sectionData.partner_number]);if(was_shown){sapeRtbHandler.sapeRTBTrackingCode(sectionData,1);sapeRtbHandler.ads[b].current_partner=sectionData.branches[sectionData.branch_number][sectionData.partner_number];}}}}}}}else if(eventData.act=='adsLoaded'){if(w.hasOwnProperty('sapeRtbHandler_95')&&w.sapeRtbHandler_95){var sapeRtbHandler=window.sapeRtbHandler_95;for(var b=0;b<sapeRtbHandler.ads.length;b++){if(sapeRtbHandler.ads[b].id==eventData.sectionId){var sectionData=sapeRtbHandler.ads[b];sapeRtbHandler.sapeRTBTrackingCode(sectionData,2);}}}}}}else{var close_pics=d.querySelectorAll('.SRTB_CLOSE');for(var key=0;key<close_pics.length;key++){close_pics[key].style.display="block";}}});}sapeRtbHandler_95.sasIds=[];function sapeRTBRun(b,rnd){if(sapeRtbHandler_95.ads[b].mobile&&sapeRtbHandler_95.sapeRTBisMobile()){sapeRtbHandler_95.ads[b].branch_number=sapeRtbHandler_95.sapeRTBGetBranchNumber(sapeRtbHandler_95.ads[b],'46,0');if(typeof sapeRtbHandler_95.ads[b].partner_number=='undefined'){sapeRtbHandler_95.ads[b].partner_number=0;}else if(!sapeRtbHandler_95.ads[b].done){sapeRtbHandler_95.ads[b].partner_number++;}
if(sapeRtbHandler_95.ads[b].branches[sapeRtbHandler_95.ads[b].branch_number][0]==16){if(typeof sapeRtbHandler_95.ads[b].sc_id!='undefined'){sapeRtbHandler_95.sasIds.push(sapeRtbHandler_95.ads[b].sc_id);sapeRtbHandler_95.ads[b].done=1;return true;}}else{var sectionData=sapeRtbHandler_95.ads[b];if(sapeRtbHandler_95.sapeRTBStartBranch(sapeRtbHandler_95.ads[b])){sapeRtbHandler_95.sapeRTBTrackingCode(sectionData,1);sapeRtbHandler_95.ads[b].done=1;sapeRtbHandler_95.ads[b].current_partner=sapeRtbHandler_95.ads[b].branches[sapeRtbHandler_95.ads[b].branch_number][sapeRtbHandler_95.ads[b].partner_number];return true;}}}else if(!sapeRtbHandler_95.ads[b].mobile){sapeRtbHandler_95.ads[b].branch_number=sapeRtbHandler_95.sapeRTBGetBranchNumber(sapeRtbHandler_95.ads[b],'7,16,0');if(typeof sapeRtbHandler_95.ads[b].partner_number=='undefined'){sapeRtbHandler_95.ads[b].partner_number=0;}else if(!sapeRtbHandler_95.ads[b].done){sapeRtbHandler_95.ads[b].partner_number++;}
if(sapeRtbHandler_95.ads[b].branches[sapeRtbHandler_95.ads[b].branch_number][0]==16){if(typeof sapeRtbHandler_95.ads[b].sc_id!='undefined'){sapeRtbHandler_95.sasIds.push(sapeRtbHandler_95.ads[b].sc_id);sapeRtbHandler_95.ads[b].done=1;return true;}}else{var sectionData=sapeRtbHandler_95.ads[b];if(sapeRtbHandler_95.sapeRTBStartBranch(sapeRtbHandler_95.ads[b])){sapeRtbHandler_95.sapeRTBTrackingCode(sectionData,1);sapeRtbHandler_95.ads[b].done=1;sapeRtbHandler_95.ads[b].current_partner=sapeRtbHandler_95.ads[b].branches[sapeRtbHandler_95.ads[b].branch_number][sapeRtbHandler_95.ads[b].partner_number];return true;}}}}
for(var b=0;b<sapeRtbHandler_95.ads.length;b++){if(sapeRtbHandler_95.ads[b].done){continue;}
if(!sapeRtbHandler_95.ads[b].popup&&!sapeRtbHandler_95.ads[b].mobile){var dv=document.getElementById('SRTB_'+sapeRtbHandler_95.ads[b].id);if(!dv||dv.children.length!==0){sapeRtbHandler_95.ads[b].done=1;continue;}}}
for(b=0;b<sapeRtbHandler_95.ads.length;b++){if(sapeRtbHandler_95.ads[b].done){continue;}
sapeRTBRun(b,0);}
if(sapeRtbHandler_95.sasIds.length>0){sapeRtbHandler_95.sapeRTBRunSas();}}
if(d.readyState=='interactive'||d.readyState=='complete'){sapeRTBonReady();}
else{bindOnReady(sapeRTBonReady);}})(window,document);function sapeRTBreadResponse(response){var w=window;if(w.hasOwnProperty('sapeRtbHandler_95')&&w.sapeRtbHandler_95){var sapeRtbHandler=w.sapeRtbHandler_95;for(var b=0;b<sapeRtbHandler.ads.length;b++){var data=sapeRtbHandler.ads[b],responseData=response[data.id];if(responseData!==undefined&&responseData!==null){data.htmlData=responseData.dt;if(data.popup&&document.getElementById('SRTB_'+data.id)){document.getElementById('SRTB_'+data.id).parentNode.removeChild(document.getElementById('SRTB_'+data.id));}
if(sapeRtbHandler.sapeRTBDrawBanner(data,16)){sapeRtbHandler.sapeRTBTrackingCode(data,1);sapeRtbHandler.ads[b].current_partner=16;}}}}}
if(!window.hasOwnProperty('_acic')||typeof window._acic!=='object'){var _acic={dataProvider:14};(function(){var e=document.createElement("script");e.type="text/javascript";e.async=true;e.src="//www.acint.net/aci.js";var t=document.getElementsByTagName("script")[0];t.parentNode.insertBefore(e,t)})()}